/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AcquireProject;

<<<<<<< HEAD
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application{

    static MainMenu mainMenu = new MainMenu();
    static UserInterface ui = new UserInterface();
=======
public class App {
>>>>>>> e8e35a8285f03a51e2023f161a595f374931c5d6

    public static void main(String[] args) {

        Application.launch();

    }

    @Override
    public void start(Stage stage) throws Exception {
        stage.setTitle("Acquire");
        stage.show();
        ui.setStage(stage);
        ui.changeScene(mainMenu.getScene());
    }



}
